### ISSUE TITLE
Supporting Visual Studio 2015 Builds with Qt5 add-on

### ISSUE THREAD

**Issue by ergodaveh** [coyote1357/OpenKJ#1]
Hello    Thanks for providing the OpenKJ.   I am interested learning more about  C++ of media apps useful for karaoke. I have loaded the executable installer for Windows. All seems good-to-go.   Do you have any build environment for windows example or advice?

**Comment by coyote1357** [comment]
Sorry for the extremely delayed response, other priorities got in the way of this project and I'm only just now picking it back up.

The way I build currently on the Windows platform is using Qt Creator from https://www.qt.io/developers/ with the Microsoft Visual Studio Express 2015 msvc compiler.

The other dependency is gstreamer 1.x, which can be acquired from https://gstreamer.freedesktop.org/

Beyond that, I'm pretty novice at developing on Windows.  I'm a Linux guy who just hacks things together through trial and error til I can get stuff to build on Windows. ;)
