### ISSUE TITLE
Second Window open on start up

### ISSUE THREAD

**Issue by ergodaveh** [coyote1357/OpenKJ#2]
The app is loaded on Win 10.
When ever the app is opened the <guessing> second Window is open, blocks the view  and refuses to close.

**Comment by coyote1357** [comment]
Now the window should revert to a non-full screen mode if you double click anywhere on it.  I need to re-work the settings dialog to keep this from happening in the first place, but that probably won't happen for a bit.

Sorry for the extremely delayed response, other priorities got in the way of this project, and I'm just now working on it again.
