### ISSUE TITLE
No Audio Output Device

### ISSUE THREAD

**Issue by johnmain** [coyote1357/OpenKJ#7]
I have successfully compiled the Master Branch on Linux Mint 18.2 following the guide for Ubuntu since Linux Mint 18.2 is based on Ubuntu 16.04.
In the setting tab under Audio Output devices there are no options listed.

I am really excited for this project since I have switched from OSX where I used kjams for Karaoke gigs I was dual booting OS X just to be able to run that app.  However, I have recently switched completely to Linux and would love to use this project.  I do need to reimport a bunch of CD+Gs into mp3+g files.  (Currently Quicktime + G format kjams uses)

**Comment by johnmain** [comment]
Actually not sure if installing libqt5multimedia5-plugins fixed it.  The output devices is still blank but I get sound now.

**Comment by coyote1357** [comment]
Ahh, yeah, I need to hide the audio output device selection part of that dialog until I work out the gstreamer logic to pull the list and change the output accordingly.  That's an in-progress feature.  Right now it just uses whatever your default output device is.  I know parts of this are sort of a mess and I need to document a lot, apologies for that.

**Comment by johnmain** [comment]
I will Start importing my mp3 + G files.  I have around 10k total songs with about a 3rd in Quicktime+g format that I will have to reimport.
I may need rename/reorganise the files in separate folders based on the naming structure as my files were purchased over the years from different sources with different naming schemes.  Took me a long time in kjams to get the library all correct.  I should have formatted the filenames instead of the Library DB.

**Comment by coyote1357** [comment]
If you need a naming format outside of what's there in the program, let me know.  It's pretty trivial to add one as long as it's something predictable with delimiters and there's a programmatic way to isolate the artist and title.

Out of curiosity, the Quicktime+G files.... is that a quicktime audio file and then the raw CDG file, or is it an all in one quicktime video file?

**Comment by johnmain** [comment]
It is a Quicktime Audio file with Raw CDG.  Xplayer plays the .mov file perfectly.  Wonder how hard it would be to support that format?  would save me a week or more reimporting.

**Comment by coyote1357** [comment]
What's the audio file's file extension?  Also, are they in a zip file, or separate files on disk?

**Comment by johnmain** [comment]
The file is SC7219-11-4 Non Blondes-What's Up.zip which contains the .mov file and cooresponding .cdg file.

**Comment by coyote1357** [comment]
It would be simpler if they were separate files, I rather shortsightedly wrote the archive handler in a way that's hardcoded to handle mp3 files specifically.  But the audio backend (gstreamer) already supports quicktime, so the capability to actually play the media is there.  Give me a bit to look back at the code and see how hard it will be to re-work the archive handler and database import stuff to be more audio format agnostic for zip files.

**Comment by johnmain** [comment]
Oh man you will make my day if you could make that happen.
Looking even at the files from the same online Vendor.  Zoom there is differences in the naming structure. I see 3 different formats for songs I purchased from Tricerisoft back a few ysers ago.

**Comment by johnmain** [comment]
I will create separate folders for the different formats.  Most should be in formats supported.  The odd ones I'll manually update to match an existing format.

**Comment by coyote1357** [comment]
I think I'm going to be able to knock the mov+g zip thing out (and ogg+g zip, wav+g zip at the same time).

Any way you can get me one of your files to test on my end before I push the code?

**Comment by johnmain** [comment]
Here is a file for you to test with.
https://drive.google.com/open?id=0B38j0IlsG9kbWm9MWlpFR21tdTA

**Comment by coyote1357** [comment]
Looks to be working. :) I just pushed the code to the repository.  Note that the naming of that file doesn't work with the naming schemes used in database update, it expects the "-" delimiter to be surrounded by whitespace like " - ".  It will still pull it in, but the whole filename will be in the discid field, not separated out into artist/title/discid.

**Comment by johnmain** [comment]
Cool I will check it out.
as long as I can search for the song and it shows up that is all that matters.
I have my books already printed with Artist and Song.

**Comment by johnmain** [comment]
Awesome.  It works great.
I will need to look at doing some renaming of files.  I might be able to write a bash script to do it.

**Comment by johnmain** [comment]
Looking at my tracks and it looks like 100% of the filenames do not have a space between the "-"

EG here is a zoom one I purchased from Tricerisoft a few years back:

Adele_-_Rolling_In_The_Deep__-_ZKG2567.ZIP

**Comment by johnmain** [comment]
What file is the Track Parse code in?  I would like to try poking around and seeing if I can add some cases to suit my files.  I Don't know c++ but I do know c# and php so I should be able to figure out what I need.
I have 5 different formats and in those 5 there are files with " - " and others with "-" and yet others with both.  I am thinking that doing a replace on " - " to "-" then split on "-" should work.  also a replace of "_" with " "

**Comment by johnmain** [comment]
BTW I have been playing some tracks and the CPU usage is very low.  You have done a good job here.  I would need to actually use this for multiple singers for a couple hours and see how it does, but so far you have a really good Karaoke player here.
Clean interface with the features that a KDJ would need.

**Comment by coyote1357** [comment]
Thank you very much.  You have the benefit of running on Linux, where I know it works well aside from a few minor bugs I'm working on and some incomplete features.  I host 5 hour shows with this software on Linux every Friday and Saturday night here in Nashville, TN with rotations averaging around 25 singers deep (and occasionally getting up to around or over 40, which makes me want to die. LOL).

**Comment by coyote1357** [comment]
Oh, to answer your previous question, the logic for splitting filenames is in dbupdatethread.cpp in the "int processKaraokeFile(QString fileName)" function.

**Comment by johnmain** [comment]
OK the file parsing code looks pretty straight forward and My ideas should work.  I will try this out tomorrow and let you know.

**Comment by johnmain** [comment]
My parse change is working.  Now I am trying to add a new pattern.  I have added to the enumin sourcedirtablemodel.h and added my case in the dbupdatethread.cpp where do you set the pattern in the Gui Drop down?

**Comment by johnmain** [comment]
My Parsing code for the "-"  is working.  I am attempting to add another Pattern to the Drop Down.
I have added My Pattern to the Enum in sourcedirtablemodel.h.
I have added the parse logic in dbupdatethread.cpp
I have added the drop down entry in dlgdatabase.cpp
I see my pattern in the drop down.  However, it doesn't appear to do anything.
is there someplace else I need to update?

**Comment by johnmain** [comment]
Ok nevermind.  The track list is blank until you hit the search.  Might be something that is should do an unfiltered search on load.

**Comment by johnmain** [comment]
Here are my changes.  


[Updates.zip](https://github.com/coyote1357/OpenKJ/files/1228802/Updates.zip)

**Comment by coyote1357** [comment]
Glad it's working out for you!  I'll definitely take a look at your mods. :). BTW, the ability to fix naming from inside the software is in the works.

**Comment by johnmain** [comment]
Just a heads up.  I Switched to SolusOS and was able to compile OpenKJ without any issues.

**Comment by coyote1357** [comment]
Good to hear!  BTW, the original reason this was opened has been fixed.  I finally figured out how to get gstreamer to list audio outputs and how to change them dynamically.  Latest version has the ability to select output devices for karaoke and break music separately in settings.

Also, I finally got around to looking at your changes that allowed you to get your collection imported.  Generally it would work, but I have a very large collection, and there are some songs that have "-" in the artist or title, and some songs with strange discid's that have lots of sections separated by "-".  That's why I was delimiting the string based on " - " instead of just "-".  I think the best thing I can do, most likely, is add the ability to create custom parsing patterns based on user inputted regex's.  Like a form that would contain 3 fields for regex entries (one for each of discid, artist,title), a field to enter an example filename, and labels that change dynamically as the user changes the regex so they'll know when they've got the right regex voodoo in.  What do you think?  Would that work for your use case?

**Comment by johnmain** [comment]
Yes that should work.  Basically per Folder File Regex.

**Comment by coyote1357** [comment]
Latest version/commit includes the regex based custom naming patterns feature. Needs a bit more polish, but I have tested it and it seems to be working well, at least on my development box.

![custompatterns](https://user-images.githubusercontent.com/6790045/29653576-009ffce0-8870-11e7-841f-ca3c41aaa872.png)

**Comment by johnmain** [comment]
I'll have a look at it.

**Comment by coyote1357** [comment]
Just committed another change to make the built in patterns work with either " " or "_" in the filenames.  It also autoreplaces "_" with " " after the result is pulled from a regex.
